-- Supabase Migration Script for KIND Application

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  service TEXT,
  location TEXT,
  status TEXT DEFAULT 'active',
  motivation TEXT,
  qualifications TEXT,
  photo_url TEXT,
  certificates_url TEXT,
  rating REAL DEFAULT 0,
  jobs_done INTEGER DEFAULT 0,
  phone_number TEXT
);

-- 2. Contact Requests Table
CREATE TABLE IF NOT EXISTS contact_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  client_name TEXT NOT NULL,
  provider_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
  provider_name TEXT NOT NULL,
  message TEXT,
  task_description TEXT,
  estimated_budget TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  approved_at TIMESTAMPTZ
);

-- 3. Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_request_id BIGINT REFERENCES contact_requests(id) ON DELETE CASCADE,
  sender_id BIGINT NOT NULL,
  sender_name TEXT NOT NULL,
  sender_role TEXT NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  read_at TIMESTAMPTZ
);

-- 4. Alerts Table
CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  severity TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Logs Table
CREATE TABLE IF NOT EXISTS logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  action TEXT NOT NULL,
  "user" TEXT NOT NULL,
  status TEXT NOT NULL,
  detail TEXT
);

-- Seed System User
INSERT INTO users (name, email, password, role, status)
VALUES ('KIND App', 'system@kind.app', '$2a$10$something-hashed-placeholder', 'SYSTEM', 'active')
ON CONFLICT (email) DO NOTHING;

-- Seed Admin User (Optional, if not registered yet)
INSERT INTO users (name, email, password, role, status)
VALUES ('Admin', 'admin@kind.com', '$2a$10$hashed-admin-pass', 'ADMIN', 'active')
ON CONFLICT (email) DO NOTHING;
